"""empty message

Revision ID: 10d9273bb93d
Revises: 594accd52d48
Create Date: 2015-07-13 15:54:28.863207

"""

# revision identifiers, used by Alembic.
revision = '10d9273bb93d'
down_revision = '594accd52d48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
