"""empty message

Revision ID: 151e2e8dd1f5
Revises: None
Create Date: 2015-05-29 16:48:00.806258

"""

# revision identifiers, used by Alembic.
revision = '151e2e8dd1f5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
