"""empty message

Revision ID: 1b5211792e49
Revises: 1b806d79bfee
Create Date: 2015-07-12 16:17:45.095404

"""

# revision identifiers, used by Alembic.
revision = '1b5211792e49'
down_revision = '1b806d79bfee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
