"""empty message

Revision ID: 1b806d79bfee
Revises: 5ae9c7a4239
Create Date: 2015-07-12 16:11:54.679861

"""

# revision identifiers, used by Alembic.
revision = '1b806d79bfee'
down_revision = '5ae9c7a4239'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
