"""empty message

Revision ID: 25bb16501130
Revises: bc4eba02c4f
Create Date: 2015-07-08 17:28:44.450291

"""

# revision identifiers, used by Alembic.
revision = '25bb16501130'
down_revision = 'bc4eba02c4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
