"""empty message

Revision ID: 281667cd842a
Revises: 43a1a18c02c9
Create Date: 2015-07-10 15:33:24.446857

"""

# revision identifiers, used by Alembic.
revision = '281667cd842a'
down_revision = '43a1a18c02c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
