"""empty message

Revision ID: 3744c20ae560
Revises: 1b5211792e49
Create Date: 2015-07-12 16:18:54.768420

"""

# revision identifiers, used by Alembic.
revision = '3744c20ae560'
down_revision = '1b5211792e49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
