"""empty message

Revision ID: 3783740499d6
Revises: 44bda5349233
Create Date: 2015-07-09 17:47:19.630075

"""

# revision identifiers, used by Alembic.
revision = '3783740499d6'
down_revision = '44bda5349233'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
