"""empty message

Revision ID: 3920bc38982f
Revises: None
Create Date: 2015-05-29 15:57:55.898049

"""

# revision identifiers, used by Alembic.
revision = '3920bc38982f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
