"""empty message

Revision ID: 43a1a18c02c9
Revises: 3c9029847ef3
Create Date: 2015-07-10 15:29:36.341956

"""

# revision identifiers, used by Alembic.
revision = '43a1a18c02c9'
down_revision = '3c9029847ef3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
