"""empty message

Revision ID: 44bda5349233
Revises: 25bb16501130
Create Date: 2015-07-09 17:42:27.042090

"""

# revision identifiers, used by Alembic.
revision = '44bda5349233'
down_revision = '25bb16501130'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
