"""empty message

Revision ID: 49c52a4a72df
Revises: None
Create Date: 2015-06-26 18:36:05.443857

"""

# revision identifiers, used by Alembic.
revision = '49c52a4a72df'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    ### end Alembic commands ###
