"""empty message

Revision ID: 59466958fdf3
Revises: 10d9273bb93d
Create Date: 2015-08-27 14:33:28.517085

"""

# revision identifiers, used by Alembic.
revision = '59466958fdf3'
down_revision = '10d9273bb93d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
