"""empty message

Revision ID: 594accd52d48
Revises: 3744c20ae560
Create Date: 2015-07-12 16:23:12.772387

"""

# revision identifiers, used by Alembic.
revision = '594accd52d48'
down_revision = '3744c20ae560'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
