"""empty message

Revision ID: 5ae9c7a4239
Revises: 281667cd842a
Create Date: 2015-07-10 15:43:58.182075

"""

# revision identifiers, used by Alembic.
revision = '5ae9c7a4239'
down_revision = '281667cd842a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
